<!-- Jquery JS -->
<script src="{{ url('') }}/js/jquery.min.js"></script>
<!-- Boostrap JS -->
<script src="{{ url('') }}/js/bootstrap.bundle.min.js"></script>
<!-- Swiper JS -->
<script src="{{ url('') }}/js/swiper-bundle.min.js"></script>
<!-- Venobox JS -->
<script src="{{ url('') }}/js/venobox.min.js"></script>
<!-- Autoomplete JS -->
<script src="{{ url('') }}/js/jquery.autocomplete.min.js"></script>
<!-- Main JS -->
<script src="{{ url('') }}/js/main.js"></script>